### ISSUE TITLE
[Request] Docs versioning

### ISSUE THREAD

**Issue by nunix** [rancher/elemental-docs#124]
The current versioning is only based in two "versions": `Next` and `Stable`.

Going forward, there's a clear need of having the docs related to a specific version.

The current Elemental version being `1.2`, the initial versions will be:
`Next` - contains the docs for the features being developed and not yet merged to a stable release
`1.2` - contains the docs for the current stable version
`1.1` - contains the docs for the previous version. The docs will be copied from the content prior to #96 

This request will be closed once the new versioning is implemented.

**Comment by kkaempf** [comment]
👍🏻 in general. However, older (obsolete) docs need a clear warning that a newer version is available, user must upgrade, and there's no support.

**Comment by crisman** [comment]
When I visit the docs page and see `1.2` and `Next 🚧` as versions and then visit the github link at the top of the page for https://github.com/rancher/elemental which gets me to https://github.com/rancher/elemental/releases and I see v1.1.5 from May 11 is the current release I am confused.

In an only `1.2` and `Next 🚧` world where are the docs for current Elemental?

Why did #176 start off as `1.0` & `1.1` last week and end up this week without either?

p.s. I understand [elemental-operator](https://github.com/rancher/elemental-operator/releases) has been at `1.2` since April, but am not sure where the logic is to set the version number from that.

**Comment by nunix** [comment]
Hi @crisman and thanks a lot for your feedback.

A new page with with the Release Notes has been added (#185) and there's a note stating that, indeed, the docs versioning is based on `elemental-operator` and not `elemental`.

Finally, as you stated correctly, I did think to base the docs versioning on `elemental`, however the team agreed on the versioning to be based on `elemental-operator` instead. So I adapted the versioning.
Please note that v1.2 == v1.1 in terms of docs, which is the current docs. `Next` contains the new docs and upon a new release, the new version will be based on it.

Hope this answers your points.

Best regards,
Nuno

**Comment by crisman** [comment]
@nunix yes the release notes provides that logic connecting operator version to docs version.  Thanks for cleaning that up.

**Comment by nunix** [comment]
Both the versioning and the release notes page have been implemented. This issue is good to be closed.
